name: release
on:
  push:
    branches:
      - release
jobs:
  compile-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PIO
        run: |  
          sudo apt-get update
          sudo apt-get install -y python3 curl
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
      - name: Compile and package
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          export VERSION=`jq .version library.json`
          export FILENAME=RHAL.tar.gz
          platformio package pack . -o $FILENAME
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          files: |
            RHAL.tar.gz
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          platformio package publish
