name: compile and release
on:
  push:
    branches:
      - release
jobs:
  compile-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PIO
        run: |  
          sudo apt-get update
          sudo apt-get install -y python3 curl
          python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
      - name: Compile and package
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          export VERSION=`jq .version library.json`
          export VERSIONTAR=`echo $VERSION | sed 's/\./\,/'`
          export FILENAME=RHAL_$VERSIONTAR.tar.gz
          platformio package pack . -o $FILENAME
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=FILENAME::$FILENAME"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            ${{ env.FILENAME }}
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}